### 项目名
spring:
  application:
    name: alibaba-cloud-learn-examples-consumer-order-80     # 项目名称
  cloud:
    consul:
      discovery:
        enabled: true ## 启用consul配置
        service-name: ${spring.application.name}  ## 服务名称
      host: 192.168.10.222 ## 服务地址
      port: 8500 ## 服务端口

### 服务端口
server:
  port: 80



logging:
  config: classpath:logback.xml