### 项目名
spring:
  application:
    name: alibaba-cloud-learn-examples-consumer-ribbon-order-80     # 项目名称


### 服务端口
server:
  port: 80

### eureka配置
eureka:
  instance:
    hostname: ${spring.application.name}  # 服务实例名称  alibaba-cloud-learn-examples-eureka-server-7001
  client:
    # 不需要注册自己
    register-with-eureka: true 
    # 标识本服务为注册中心 职责就是维护服务实例 并不需要取检索服务
    fetch-registry: true 
    service-url:
       ## 图形界面交互地址
       defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/

logging:
  config: classpath:logback.xml