### 项目名
spring:
  application:
    name: alibaba-cloud-learn-examples-consumer-order-80     # 项目名称
### nacos配置
  cloud: 
    nacos:
      discovery:
        server-addr: 192.168.10.222:8848
        enabled: true
        
management:
  endpoints:
    web:
      exposure:
        include: "*"
### 服务端口
server:
  port: 80




logging:
  config: classpath:logback.xml