### 项目名
spring:
  application:
    name: alibaba-cloud-learn-examples-getway-server-9000    # 项目名称
  cloud:
    gateway:
      enabled: true
      routes:
        - id: alibaba-cloud-learn-examples-gateway-provider-payment ## 路由编号  建议使用服务名称 唯一标识
#          uri: http://localhost:8001  ## 请求地址
          uri: lb://alibaba-cloud-learn-examples-gateway-provider-payment  ## 请求地址
          predicates:                 ## 断言 路径相匹配的路由
            - Path=/payment/**,/admin/**   ## 根据路径匹配路由
#            - Cookie=username, julong   ## cookie配置示例
      discovery:
        locator:
          enabled: true ## 启用动态路由
### 服务端口
server:
  port: 9000

### eureka配置
eureka:
  instance:
    hostname: ${spring.application.name}  # 服务实例名称  alibaba-cloud-learn-examples-eureka-server-7001
  client:
    # 不需要注册自己
    register-with-eureka: true 
    # 标识本服务为注册中心 职责就是维护服务实例 并不需要取检索服务
    fetch-registry: true 
    service-url:
       ## 图形界面交互地址
       defaultZone: http://192.168.10.128:7001/eureka/

    
## 日志配置
logging:
  config: classpath:logback.xml