### 项目名
spring:
  application:
    name: alibaba-cloud-learn-examples-hystrix-feign-consumer-order    # 项目名称


### 服务端口
server:
  port: 80

### eureka配置
eureka:
  instance:
    hostname: ${spring.application.name}  # 服务实例名称  alibaba-cloud-learn-examples-eureka-server-7001
  client:
    # 不需要注册自己
    register-with-eureka: true 
    # 标识本服务为注册中心 职责就是维护服务实例 并不需要取检索服务
    fetch-registry: true 
    service-url:
       ## 图形界面交互地址
       defaultZone: http://localhost:7001/eureka/

logging:
  config: classpath:logback.xml
  
  
## 设置feign客户端超时
#feign:
#  client:
#    config:
#      default:
#        connectTimeout: 5000 ## 设置建立连接后从服务器读取数据的所用时间
#        readTimeout: 5000 ## 设置双方连接时间超时
#        loggerLevel: basic ## 日志级别

feign:
  hystrix:
    enabled: true ## 启用服务熔断
  