### 项目名
spring:
  application:
    name: alibaba-cloud-learn-examples-zookeeper-provider-payment     # 项目名称
  datasource:
    driver-class-name: org.gjt.mm.mysql.Driver              # 驱动名称
    url: jdbc:mysql://192.168.10.222:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root                                          # 账户
    password: root                                          # 密码
    type: com.alibaba.druid.pool.DruidDataSource            # 数据源操作类型
  cloud:        ### 配置 zookeeper地址
    zookeeper:
      connect-string: 192.168.10.222:2181

### 服务端口
server:
  port: 8004

### mybaits配置
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.julong.**.entity
### 日志配置
logging:
  config: classpath:logback.xml
  
  
### zookeeper配置
  