### 项目名
spring:
  application:
    name: alibaba-cloud-learn-examples-sentinel-provider-payment     # 项目名称
  datasource:
    driver-class-name: org.gjt.mm.mysql.Driver              # 驱动名称
    url: jdbc:mysql://192.168.10.222:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root                                          # 账户
    password: root                                          # 密码
    type: com.alibaba.druid.pool.DruidDataSource            # 数据源操作类型
### nacos配置
  cloud: 
    nacos:
      discovery:
        server-addr: 192.168.10.222:8848
        enabled: true
        service: ${spring.application.name}
    sentinel:
      enabled: true ## 启用 sentinel
      transport:
        port: 8719
        dashboard: 127.0.0.1:8080    ## 面板ui界面    
      datasource:  ## 持久化配置
        ds1:
          nacos:
            server-addr: 192.168.10.222:8848
            data-id: alibaba-cloud-learn-examples-sentinel-provider-payment
            group-id: DEFAULT_GROUP
            data-type: json
            rule-type: flow
management:
  endpoints:
    web:
      exposure:
        include: "*"
### 服务端口
server:
  port: 9001

### mybaits配置
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.julong.**.entity
### 日志配置
logging:
  config: classpath:logback.xml
  
