### 项目名
spring:
  application:
    name: alibaba-cloud-learn-examples-config-git-server    # 项目名称

  cloud:
    config:
      enabled: true   ##启用config配置
      server:
        git:
          uri: https://gitee.com/julong/spring-cloud-config.git
          search-paths:
            - spring-cloud-config
          default-label: master    ## 分支信息
          username: koudailidexiaolong@163.com   ## 账号密码信息
          password: xiaolong0627
### 服务端口
server:
  port: 7007

### eureka配置
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}  # 服务实例名称  alibaba-cloud-learn-examples-provider-payment
    prefer-ip-address: true ## 显示真实IP地址
  client:
    # 不需要注册自己
    register-with-eureka: true 
    # 标识本服务为注册中心 职责就是维护服务实例 并不需要取检索服务
    fetch-registry: true 
    service-url:
       ## 图形界面交互地址
       defaultZone: http://localhost:7001/eureka/
    
## 日志配置
logging:
  config: classpath:logback.xml
  
