### 项目名
spring:
  application:
    name: alibaba-cloud-learn-examples-zuul-server    # 项目名称


### 服务端口
server:
  port: 7007

### eureka配置
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}  # 服务实例名称  alibaba-cloud-learn-examples-provider-payment
    prefer-ip-address: true ## 显示真实IP地址
  client:
    # 不需要注册自己
    register-with-eureka: true 
    # 标识本服务为注册中心 职责就是维护服务实例 并不需要取检索服务
    fetch-registry: true 
    service-url:
       ## 图形界面交互地址
       defaultZone: http://localhost:7001/eureka/
    
## 日志配置
logging:
  config: classpath:logback.xml
  
## zuul网关配置 
zuul:
  routes:
    users:
      path: /myusers/**
      serviceId: alibaba-cloud-learn-examples-zuul-provider-payment
  ignored-patterns: /admin/**  ## 忽略带admin请求的url
        
  prefix: /api  ## 配置统一访问路径